/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package esame.lbd.pkg2016;

import static esame.lbd.pkg2016.Principale.mostraErroriSwing;
import java.awt.Color;
import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Types;

/**
 *
 * @author Maurizio Minieri Alessio Spina
 */
public class Caselli extends javax.swing.JDialog {

     boolean premutoexit;
     private static final String NOME_FUNZIONE = "PERCORSO_CASELLI_MOD"; 
    
    public Caselli(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        tCasello1.requestFocus(); 
        this.getRootPane().setDefaultButton(bControlla);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bBack = new javax.swing.JButton();
        tCasello1 = new javax.swing.JTextField();
        tCasello2 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        bExit = new javax.swing.JButton();
        bControlla = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TextArea = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bBack.setText("Back");
        bBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBackActionPerformed(evt);
            }
        });
        getContentPane().add(bBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 417, -1, -1));

        tCasello1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tCasello1ActionPerformed(evt);
            }
        });
        getContentPane().add(tCasello1, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 83, 88, -1));

        tCasello2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tCasello2ActionPerformed(evt);
            }
        });
        getContentPane().add(tCasello2, new org.netbeans.lib.awtextra.AbsoluteConstraints(348, 83, 88, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Inserisci casello1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 49, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Inserisci casello2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(348, 49, -1, -1));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Maurizio Minieri & Alessio Spina");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        bExit.setText("Exit");
        bExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bExitActionPerformed(evt);
            }
        });
        getContentPane().add(bExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(459, 417, -1, -1));

        bControlla.setText("Controlla");
        bControlla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bControllaActionPerformed(evt);
            }
        });
        getContentPane().add(bControlla, new org.netbeans.lib.awtextra.AbsoluteConstraints(213, 109, -1, -1));

        TextArea.setEditable(false);
        TextArea.setColumns(20);
        TextArea.setLineWrap(true);
        TextArea.setRows(5);
        jScrollPane1.setViewportView(TextArea);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 138, 490, 273));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/esame/lbd/pkg2016/autostrada2.jpg"))); // NOI18N
        jLabel5.setText("jLabel5");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(-640, -220, 1180, 680));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tCasello1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tCasello1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tCasello1ActionPerformed

    private void tCasello2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tCasello2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tCasello2ActionPerformed

    private void bBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBackActionPerformed
        dispose();
        Principale p=new Principale(1);
    }//GEN-LAST:event_bBackActionPerformed

    private void bExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bExitActionPerformed
        premutoexit=true;
        try {
         Database.getDefaultConnection().close();  
      } catch (SQLException e) {
         mostraErroriSwing(this,e);
      }
      dispose();    //chiude la finestra
    }//GEN-LAST:event_bExitActionPerformed

    private void bControllaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bControllaActionPerformed
       Collegamenti();
    }//GEN-LAST:event_bControllaActionPerformed

     private void Collegamenti() 
     {
         CallableStatement cs = null;
         String CAS1 =  tCasello1.getText();
         String CAS2 =   tCasello2.getText();
        
         
         
         
          try 
      {
         Connection conn = Database.getDefaultConnection();   
         cs = conn.prepareCall("BEGIN ?:=" + NOME_FUNZIONE + "(?,?); END;");  
       
       
          cs.registerOutParameter(1, Types.VARCHAR);                           
          
          
             
          cs.setString(2, CAS1.toUpperCase());                     
                                                              
         
         
          cs.setString(3, CAS2.toUpperCase());                   
                                                                
                                                                  
       
          
         cs.execute();                    
        
         
         
          TextArea.setText(cs.getString(1));
     }
        catch (SQLException e) 
      {
         mostraErroriSwing(this,e);   
      } 
      finally 
      {
         if (cs != null) {         
            try {
               cs.close();                
            } catch (SQLException e) {
               mostraErroriSwing(this,e);
            }
         }
      }   
          
          
     }
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea TextArea;
    private javax.swing.JButton bBack;
    private javax.swing.JButton bControlla;
    private javax.swing.JButton bExit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField tCasello1;
    private javax.swing.JTextField tCasello2;
    // End of variables declaration//GEN-END:variables
}
