/*
 * Login.java
 *
 * Modified on 2016-06-09
 */
package esame.lbd.pkg2016;

import java.sql.SQLException;
import javax.swing.JOptionPane;
import org.jdesktop.beansbinding.*;

/**
 * Finestra di dialogo per impostare i parametri di connessione al DataBase.
 *
 * @author Maurizio
 * @author Minieri
 * @version 2016
 */
public class LoginDB extends javax.swing.JDialog {

   /**
    * Costante per indicare la pressione del pulsante Annulla.
    */
   public static final int PREMUTO_ANNULLA = 0;
   /**
    * Costante per indicare la pressione del pulsante OK.
    */
    boolean PREMUTO_LOGIN=false;

   /**
    * Costruisce la finestra tenendo traccia del frame chiamante.
    *
    * @param parent Frame chiamante
    * @param modal Specifica se la finestra di dialogo blocca l'input utente
    * sulla finestra chiamante
    */
   public LoginDB(java.awt.Frame parent, boolean modal) {
      super(parent, modal);
      initComponents();
//      this.tHost.setText(Database.host);
//      this.tPorta.setText("" + Database.porta);
//      this.tServizio.setText(Database.servizio);
//      this.tSchema.setText(Database.schema);
//      this.tUser.setText(Database.user);
//      this.tPassword.setText(Database.password);
      this.tUser.requestFocus();
      getRootPane().setDefaultButton(bLogin);
   }
   /**
    * Variabile intera che registra quale pulsante &egrave; stato premuto.
    */
   private int premuto;

   /**
    * Restituisce il contenuto del campo premuto, che
    * rappresenta il pulsante premuto dall'utente
    *
    * @return intero che descrive il pulsante premuto
    */
   public int getPremuto() {
      return premuto;
   }

   /**
    * This method is called from within the constructor to initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is always
    * regenerated by the Form Editor.
    */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        bLogin = new javax.swing.JButton();
        bAnnulla = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        tHost = new javax.swing.JTextField();
        tServizio = new javax.swing.JTextField();
        tPorta = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tPassword = new javax.swing.JPasswordField();
        tSchema = new javax.swing.JTextField();
        checkSchema = new javax.swing.JCheckBox();
        tUser = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setLocation(new java.awt.Point(480, 300));
        setResizable(false);

        bLogin.setText("Login");
        bLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bLoginActionPerformed(evt);
            }
        });

        bAnnulla.setText("Annulla");
        bAnnulla.setDefaultCapable(false);
        bAnnulla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAnnullaActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel6.setText("Login");

        jLabel1.setText("Host");

        jLabel2.setText("Porta");

        jLabel3.setText("Servizio");

        jLabel7.setText("Schema");

        tHost.setText("localhost");

        tServizio.setText("XE");

        tPorta.setText("1521");

        jLabel4.setText("Utente");

        jLabel5.setText("Password");

        tPassword.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        tPassword.setPreferredSize(new java.awt.Dimension(30, 20));

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, tUser, org.jdesktop.beansbinding.ELProperty.create("${text}"), tSchema, org.jdesktop.beansbinding.BeanProperty.create("text"), "bindSchema");
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, checkSchema, org.jdesktop.beansbinding.ELProperty.create("${!selected}"), tSchema, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        tSchema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tSchemaActionPerformed(evt);
            }
        });

        checkSchema.setSelected(true);
        checkSchema.setText("=Utente");
        checkSchema.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                checkSchemaStateChanged(evt);
            }
        });

        tUser.setText("auto");
        tUser.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                tUserComponentAdded(evt);
            }
        });
        tUser.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                tUserCaretUpdate(evt);
            }
        });
        tUser.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
                tUserAncestorMoved(evt);
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                tUserAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
                tUserAncestorRemoved(evt);
            }
        });
        tUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tUserMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tUserMouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tUserMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tUserMouseReleased(evt);
            }
        });
        tUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tUserActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(87, 87, 87)
                .add(bLogin)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 108, Short.MAX_VALUE)
                .add(bAnnulla)
                .add(83, 83, 83))
            .add(layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(31, 31, 31)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabel2)
                            .add(jLabel1)
                            .add(jLabel3)
                            .add(jLabel7)
                            .add(jLabel4)
                            .add(jLabel5))
                        .add(10, 10, 10)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(layout.createSequentialGroup()
                                .add(tSchema, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 193, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(checkSchema))
                            .add(tUser, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 282, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                    .add(layout.createSequentialGroup()
                        .add(97, 97, 97)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(tServizio, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 71, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(tPorta, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 49, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(tHost, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 231, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(tPassword, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 282, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                    .add(layout.createSequentialGroup()
                        .add(47, 47, 47)
                        .add(jLabel6, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 73, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(new java.awt.Component[] {tHost, tPassword, tPorta, tServizio}, org.jdesktop.layout.GroupLayout.HORIZONTAL);

        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel6)
                .add(25, 25, 25)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel1)
                    .add(tHost, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(tPorta, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel2))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(tServizio, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel3))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel7)
                    .add(tSchema, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(checkSchema))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel4)
                    .add(tUser, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(tPassword, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel5))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 17, Short.MAX_VALUE)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(bLogin)
                    .add(bAnnulla))
                .add(26, 26, 26))
        );

        layout.linkSize(new java.awt.Component[] {tPassword, tUser}, org.jdesktop.layout.GroupLayout.VERTICAL);

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

   /**
    * Registra la pressione del pulsante Annulla.
    *
    * @param evt Evento di pressione del pulsante Annulla
    */
    private void bAnnullaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAnnullaActionPerformed
       premuto = PREMUTO_ANNULLA;
       dispose();
    }//GEN-LAST:event_bAnnullaActionPerformed

   /**
    * Registra la pressione del pulsante Login.
    *
    * @param evt Evento di pressione del pulsante Login
    */
    private void bLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bLoginActionPerformed
       Database.host = tHost.getText();
       try {
          Database.porta = Integer.parseInt(tPorta.getText());
       } catch (NumberFormatException e) {
          JOptionPane.showMessageDialog(this, "La porta dev'essere"
                  + " un numero", "Errore", JOptionPane.ERROR_MESSAGE);
       }
       Database.schema = tSchema.getText();
       Database.servizio = tServizio.getText();
       Database.user = tUser.getText();
       Database.password = new String(tPassword.getPassword());
       try {
          Database.setDefaultConnection(Database.nuovaConnessione());
          //new Main().setVisible(true);
           PREMUTO_LOGIN=true;
          dispose();
       } catch (SQLException e) {
          Database.mostraErroriSwing(this, e);
          // Per dare informazioni piÃ¹ comprensibili all'utente:
          //JOptionPane.showMessageDialog(this, "Connessione fallita (credenziali"
          //        + " errate?)", "Errore", JOptionPane.ERROR_MESSAGE);
       }
    }//GEN-LAST:event_bLoginActionPerformed

   private void checkSchemaStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_checkSchemaStateChanged
      // TODO add your handling code here:
      Binding binding = bindingGroup.getBinding("bindSchema");
      if (!checkSchema.isSelected() && binding.isBound()) {
         binding.unbind();
      } else if (checkSchema.isSelected() && !binding.isBound()) {
         binding.bind();
      }
   }//GEN-LAST:event_checkSchemaStateChanged

    private void tSchemaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tSchemaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tSchemaActionPerformed

    private void tUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tUserActionPerformed

    private void tUserAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_tUserAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_tUserAncestorAdded

    private void tUserAncestorMoved(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_tUserAncestorMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_tUserAncestorMoved

    private void tUserAncestorRemoved(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_tUserAncestorRemoved
        // TODO add your handling code here:
    }//GEN-LAST:event_tUserAncestorRemoved

    private void tUserCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_tUserCaretUpdate
        // TODO add your handling code here:
    }//GEN-LAST:event_tUserCaretUpdate

    private void tUserComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_tUserComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_tUserComponentAdded

    private void tUserMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tUserMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_tUserMousePressed

    private void tUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tUserMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tUserMouseClicked

    private void tUserMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tUserMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_tUserMouseEntered

    private void tUserMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tUserMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_tUserMouseReleased

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAnnulla;
    private javax.swing.JButton bLogin;
    private javax.swing.JCheckBox checkSchema;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField tHost;
    private javax.swing.JPasswordField tPassword;
    private javax.swing.JTextField tPorta;
    private javax.swing.JTextField tSchema;
    private javax.swing.JTextField tServizio;
    private javax.swing.JTextField tUser;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
