/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package esame.lbd.pkg2016;

import java.awt.Color;
import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Types;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Maurizio
 */
public class Principale extends javax.swing.JFrame {

    private static final String NOME_FUNZIONE = "CHECK_TARGA"; 
    
    public Principale(int volta)
    {
        initComponents();
        
        if(volta==0)
        {
         LoginDB c = new LoginDB(this,true);
         
        
         c.setVisible(true); 
        
         if (!c.PREMUTO_LOGIN) 
         {
             dispose();
         }
         else 
         {
             
             Scelta s=new Scelta(this,true);
             s.setVisible(true);
             
             if(s.premutoCaselli)
             {
                 
                 Caselli cas = new Caselli(this,true);
                 cas.setVisible(true);
                 
                 this.getRootPane().setDefaultButton(bControlla);
                 if(cas.premutoexit)
                     dispose();
             }
             else if(s.premutoTarga)
             {
                 
                 this.setVisible(true);
                 this.getRootPane().setDefaultButton(bControlla);
                 
             }
         }
        }
         else           //volta = 1
         {
  
              Scelta s=new Scelta(this,true);
              s.setVisible(true);
              
           if(s.premutoCaselli)
           {
              
                 Caselli cas = new Caselli(this,true);
                 cas.setVisible(true); 
                 cas.getRootPane().setDefaultButton(bControlla); 
                 if(cas.premutoexit)
                     dispose();
           }
           else if(s.premutoTarga)
           { 
                     
                      this.setVisible(true); 
                      this.getRootPane().setDefaultButton(bControlla);     
            }     
        
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lTitle = new javax.swing.JLabel();
        bExit = new javax.swing.JButton();
        bBack = new javax.swing.JButton();
        Label = new javax.swing.JLabel();
        tTarga = new javax.swing.JTextField();
        bControlla = new javax.swing.JButton();
        lLabel = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Tabella = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lTitle.setText("Esame Minieri");
        getContentPane().add(lTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 230, -1));

        bExit.setText("Exit");
        bExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bExitActionPerformed(evt);
            }
        });
        getContentPane().add(bExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 543, -1, -1));

        bBack.setText("Back");
        bBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBackActionPerformed(evt);
            }
        });
        getContentPane().add(bBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 543, -1, -1));

        Label.setText("Scrivi Targa");
        getContentPane().add(Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(378, 26, 70, 26));

        tTarga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tTargaActionPerformed(evt);
            }
        });
        getContentPane().add(tTarga, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 58, 166, 30));

        bControlla.setText("Controlla");
        bControlla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bControllaActionPerformed(evt);
            }
        });
        getContentPane().add(bControlla, new org.netbeans.lib.awtextra.AbsoluteConstraints(364, 99, -1, -1));

        lLabel.setText("—");
        getContentPane().add(lLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(113, 131, 626, 23));

        Tabella.setAutoCreateRowSorter(true);
        Tabella.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"", "", "", "", "", "", "", "", "", ""},
                {"", "", "", "", "", "", "", "", "", ""},
                {"", "", "", "", "", "", "", "", "", ""},
                {"", "", "", "", "", "", "", "", "", ""},
                {"", null, null, "", null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "SVINCOLO", "COD_TRATTA", "USCITA_IN_TRATTA", "TIPOLOGIA", "DATI_PASSAGGIO", "ID_CASELLO", "DATI_PASS_1", "ID_TUTOR", "COD_TRATTA_1", "DATI_PASS_2"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Tabella.setEnabled(false);
        Tabella.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                TabellaAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        Tabella.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                TabellaComponentHidden(evt);
            }
        });
        Tabella.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                TabellaPropertyChange(evt);
            }
        });
        Tabella.addVetoableChangeListener(new java.beans.VetoableChangeListener() {
            public void vetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {
                TabellaVetoableChange(evt);
            }
        });
        jScrollPane2.setViewportView(Tabella);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 810, 260));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tTargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tTargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tTargaActionPerformed

    private void TabellaAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_TabellaAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_TabellaAncestorAdded

    private void TabellaComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_TabellaComponentHidden
        // TODO add your handling code here:
    }//GEN-LAST:event_TabellaComponentHidden

    private void TabellaPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_TabellaPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_TabellaPropertyChange

    private void TabellaVetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {//GEN-FIRST:event_TabellaVetoableChange
        // TODO add your handling code here:
    }//GEN-LAST:event_TabellaVetoableChange

    private void bExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bExitActionPerformed
      try {
         Database.getDefaultConnection().close();   //chiude la connessione al database
      } catch (SQLException e) {
         mostraErroriSwing(this,e);
      }
      dispose();    //chiude la finestra
    }//GEN-LAST:event_bExitActionPerformed

    private void bBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBackActionPerformed
      dispose();
         Principale p=new Principale(1);
    }//GEN-LAST:event_bBackActionPerformed

    private void bControllaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bControllaActionPerformed
        eseguiControllo();
    }//GEN-LAST:event_bControllaActionPerformed

    
    private void eseguiControllo() 
   {
      
       String Str =  tTarga.getText();
       CallableStatement cs = null;
       PreparedStatement OUTPUT = null;
       ResultSet rs=null;
       ResultSet rs2=null;
        DefaultTableModel TabellaModel;
       
        String[] tableHeaders={"SVINCOLO","COD_TRATTA","USCITA_IN_TRATTA","TIPOLOGIA","DATI_PASSAGGIO","ID_CASELLO","DATI_PASSAGGIO_1","ID_TUTOR","COD_TRATTA_1","DATI_PASSAGGIO_2"};
        Object[][] tableData={{"","","","","","","","","",""},{"","","","","","","","","",""},{"","","","","","","","","",""},{"","","","","","","","","",""},{"","","","","","","","","",""},{"","","","","","","","","",""},{"","","","","","","","","",""},{"","","","","","","","","",""},{"","","","","","","","","",""},{"","","","","","","","","",""},{"","","","","","","","","",""},{"","","","","","","","","",""},{"","","","","","","","","",""},{"","","","","","","","","",""},{"","","","","","","","","",""},{"","","","","","","","","",""},{"","","","","","","","","",""},{"","","","","","","","","",""},{"","","","","","","","","",""},{"","","","","","","","","",""},{"","","","","","","","","",""},{"","","","","","","","","",""},{"","","","","","","","","",""},{"","","","","","","","","",""},{"","","","","","","","","",""},{"","","","","","","","","",""},{"","","","","","","","","",""},{"","","","","","","","","",""}};
        
     String Query="SELECT DISTINCT S.SVINCOLO, SS.COD_TRATTA,SS.USCITA_IN_TRATTA, SS.TIPOLOGIA, S.DATI_PASSAGGIO, P.ID_CASELLO, P.DATI_PASSAGGIO, T.ID_TUTOR, T.COD_TRATTA, T.DATI_PASSAGGIO\n" +
"FROM PASSAGGIO_SVINCOLO S\n" +
" INNER JOIN SVINCOLO SS ON S.SVINCOLO=SS.ID_SVINCOLO\n" +
" LEFT OUTER JOIN PASSAGGIO_CASELLO P ON SS.ID_SVINCOLO=P.SVINCOLO\n" +
" LEFT OUTER JOIN TUTOR T ON T.COD_TRATTA=SS.COD_TRATTA\n" +
"WHERE S.VEICOLO= '"+ Str.toUpperCase() +"' ";
      
     
      
      try 
      {
         Connection conn = Database.getDefaultConnection();   
         cs = conn.prepareCall("BEGIN ?:=" + NOME_FUNZIONE + "(?); END;");  
       
         
         cs.registerOutParameter(1, Types.CHAR);
         cs.setString(2, tTarga.getText());   
  
         cs.executeQuery();                   
        
         
          
         
         if (cs.getString(1).equals("-1")||tTarga.getText().length()== 0)
         {
              lLabel.setForeground(Color.RED);
               lLabel.setText("LUNGHEZZA TARGA ERRATA");
                TabellaModel = new DefaultTableModel(tableData,tableHeaders);
                 Tabella.setModel(TabellaModel);
         }
         else if (cs.getString(1).equals("0")) {     
            lLabel.setForeground(Color.RED);   
            lLabel.setText("TARGA SCRITTA IN MODO ERRATO");   
            TabellaModel = new DefaultTableModel(tableData,tableHeaders);
                 Tabella.setModel(TabellaModel);
         } 
         else
         {
            lLabel.setForeground(Color.decode("0x009900"));  
            lLabel.setText("Targa scritta in modo valido");    
            OUTPUT=conn.prepareStatement(Query);
            System.out.println("OUTPUT"+OUTPUT);
            rs=OUTPUT.executeQuery();
             System.out.println("RS"+rs);
           
       
               
               int k=0;
               
              
               
            while(rs.next())
            {
                for(int i=0;i<10;i++)
                {
                
                      tableData[k][i]=rs.getString(i+1);
                    
                }
              
                k++;
            }
                TabellaModel = new DefaultTableModel(tableData,tableHeaders);
                Tabella.setModel(TabellaModel);
                    
             
              
              
           }

      }
      catch (SQLException e) 
      {
         mostraErroriSwing(this,e);   
      } 
      finally 
      {
         if (cs != null) {        
            try {
               cs.close();                
            } catch (SQLException e) {
               mostraErroriSwing(this,e);
            }
         }
      }      
   }
    
    
    
    static public void mostraErroriSwing(java.awt.Component thrower,SQLException e) {
      String msg;
      msg = e.getMessage() + "\n";
      msg += "SQLState= " + e.getSQLState() + "\n";
                                                  
      JOptionPane.showMessageDialog(thrower, msg, "Errore " + e.getErrorCode(),       
              JOptionPane.ERROR_MESSAGE);       
   }
    
    
    
    
    
    
    
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                 Principale p=new Principale(0);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Label;
    private javax.swing.JTable Tabella;
    private javax.swing.JButton bBack;
    private javax.swing.JButton bControlla;
    private javax.swing.JButton bExit;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lLabel;
    private javax.swing.JLabel lTitle;
    private javax.swing.JTextField tTarga;
    // End of variables declaration//GEN-END:variables
}
