/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package esame.lbd.pkg2016;

/**
 *
 * @author Maurizio Minieri Alessio Spina
 */
public class Scelta extends javax.swing.JDialog {

   boolean premutoTarga=false;    
    boolean premutoCaselli=false;  
   
    public Scelta(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tTarga = new javax.swing.JButton();
        tCaselli = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tTarga.setText("Targa");
        tTarga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tTargaActionPerformed(evt);
            }
        });
        getContentPane().add(tTarga, new org.netbeans.lib.awtextra.AbsoluteConstraints(131, 161, -1, -1));

        tCaselli.setText("Caselli");
        tCaselli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tCaselliActionPerformed(evt);
            }
        });
        getContentPane().add(tCaselli, new org.netbeans.lib.awtextra.AbsoluteConstraints(286, 161, -1, -1));

        jLabel1.setFont(new java.awt.Font("Rockwell", 1, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 255, 102));
        jLabel1.setText("Clicca 'Targa' per ricostruire il percorso del veicolo ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 440, 28));

        jLabel2.setFont(new java.awt.Font("Rockwell", 1, 15)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 255, 0));
        jLabel2.setText("Clicca 'Caselli' per vedere i percorsi autostradali che li collegano");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, 30));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Maurizio Minieri & Alessio Spina");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/esame/lbd/pkg2016/autostradamia.png"))); // NOI18N
        jLabel4.setText("jLabel4");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(-50, 0, 580, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tTargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tTargaActionPerformed
        premutoTarga=true;
        dispose();
    }//GEN-LAST:event_tTargaActionPerformed

    private void tCaselliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tCaselliActionPerformed
        premutoCaselli=true;
        dispose();
    }//GEN-LAST:event_tCaselliActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton tCaselli;
    private javax.swing.JButton tTarga;
    // End of variables declaration//GEN-END:variables
}
